os: linux
dist: trusty
language: python
services:
  - docker

branches:
  only:
    - master

jobs:
  include:
    - stage: check-build
      name: "Build Docker container"
      script:
        - make build

stages:
  - check-build
